config/routes.rb
Rails.application.routes.draw do

    resources :articles
  # get '/articles', to: 'articles#index'

  # get '/article/:id', to: 'articles#show'

  # get '/articles/new', to: 'articles#new'
  # post '/articles', to: 'articles#create'

  # get '/article/:id/edit', to: 'articles#edit'
  # patch '/article/:id', to:'articles#update'

  # delete 'article/:id', to: 'articles#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    # @article = Article.find(params[:id])
  end

  def new
    # @article = article.new
  end

  def create
    # article = Article.create(article_params)
    # redirect_to article_path(article)
  end

  def edit
  #   @article = article.find(params[:id])
  end

  def update
    # article = article.find(params[:id])
    # article.update(article_params)
    # redirect_to article_path(article)
  end

  def destroy
    # article = article.find(params[:id])
    # article.destroy
    # redirect_to articles_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create(article_params)
    redirect_to article_path(article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    article.update(article_params)
    redirect_to article_path(article)
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit an article</h1>
<%= form_for @article do |f| %>
  <%= f.label :title, value: 'Title' %>
  <%=f.text_field :title %>
  <br>
  <%= f.label :content, value: 'Pokemon name' %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
  <br>
  <%= link_to 'Backs to articles', articles_path %>
<% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul>
  <%@articles.each do |article| %>
    <%= link_to article.title, article_path(article)  %>

    <p></p>
    <br>
    <%= link_to "delete", article_path(article), method: :delete%>
  <% end %>

</ul>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h3><%= @article.content %></h3>
<%= link_to 'Backs to articles', articles_path %>
<br>
<%= link_to 'Edit this article', edit_article_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>